# Generated by Django 5.0.14 on 2025-11-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="employee_id",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
