# Generated by Django 5.0.14 on 2025-11-20 06:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_driverprofile_delete_driver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverprofile",
            name="employee_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
