# Generated by Django 5.0.14 on 2025-12-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("tree", "Tree"), ("ornament", "Ornament"), ("nft", "NFT")],
                max_length=50,
            ),
        ),
    ]
